---
- name: Include Netdata Install Option Definitions
  include_vars:
    file: install-option-definitions.yml

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_script.path }}/{{ netdata_install_script.sh }} --dont-wait --dont-start-it"

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_cmd + ' ' + netdata_auto_update }}"
  when: netdata_install_opts.auto_update

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_cmd + ' ' + netdata_disable_go }}"
  when: netdata_install_opts.disable_go

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_cmd + ' ' + netdata_disable_lto }}"
  when: netdata_install_opts.disable_lto

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_cmd + ' ' + netdata_disable_plugin_freeipmi }}"
  when: netdata_install_opts.disable_plugin_freeipmi

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_cmd + ' ' + netdata_disable_plugin_nfacct }}"
  when: netdata_install_opts.disable_plugin_nfacct

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_cmd + ' ' + netdata_disable_telemetry }}"
  when: netdata_install_opts.disable_telemetry

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_cmd + ' ' + netdata_disable_x86_sse }}"
  when: netdata_install_opts.disable_x86_sse

- name: Set Base Netdata Installation Variable
  set_fact:
    netdata_install_cmd: "{{ netdata_install_cmd + ' ' + netdata_installation_path }}"
  when: not netdata_install_opts.installation_path == 'default'