---
- name: Ensure Apt Cache Is up to Date (Apt)
  become: true
  apt:
    update_cache: true
    cache_valid_time: 360
  when:
    - ansible_os_family == 'Debian'

- name: Ensure Netdata Dependencies Are Present (General)
  become: true
  package:
    name: "{{ netdata_packages_general }}"
    state: present

- name: Ensure Netdata Dependencies Are Present (Apt)
  become: true
  apt:
    name: "{{ netdata_packages_apt }}"
    state: present
    update_cache: true
    cache_valid_time: 360
  when:
    - ansible_os_family == 'Debian'

- name: Ensure Netdata Dependencies Are Present (Dnf)
  become: true
  dnf:
    name: "{{ netdata_packages_dnf }}"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- name: Ensure Netdata Dependencies Are Present (Yum)
  become: true
  yum:
    name: "{{ netdata_packages_yum }}"
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'CentOS'

- name: Include Build Sequence of Installation Command
  include_tasks:
    file: install-cmd.yml

- name: Ensure Netdata Github Repo Is up to Date
  become: true
  git:
    repo: "{{ netdata_repo }}"
    dest: "{{ netdata_source_dir }}"
    version: "{{ netdata_repo_version }}"
    depth: 100

- name: Set Netdata Service File Variables (Systemd)
  set_fact:
    netdata_service_permission: 0664
    netdata_service_source: "{{ netdata_source_dir }}/system/netdata.service"
    netdata_service_installation: /usr/lib/systemd/system/netdata.service
  when: ansible_service_mgr | lower == 'systemd'

- name: Set Netdata Service File Variables (Upstart)
  set_fact:
    netdata_service_permission: 0755
    netdata_service_source: "{{ netdata_source_dir }}/system/netdata-init-d"
    netdata_service_installation: /etc/rc.d/init.d/netdata
  when: ansible_service_mgr | lower == 'upstart'

- name: Check for Existing Netdata Service
  become: true
  stat:
    path: "{{ netdata_service_installation }}"
  register: netdata_service

- name: Stop Netdata Service If Present
  become: true
  service: name=netdata state=stopped
  when: netdata_service.stat.exists

- name: Ensure Netdata Is Installed and up to Date
  become: true
  command: "{{ netdata_install_cmd }}"
  args:
    chdir: "{{ netdata_source_dir }}"
    creates: /usr/sbin/netdata

- name: Configure Netdata Service Files
  become: true
  copy:
    src: "{{ netdata_service_source }}"
    remote_src: true
    dest: "{{ netdata_service_installation }}"
    mode: "{{ netdata_service_permission }}"
  notify: Restart and Enable Netdata

- name: Include Configuration File
  include_tasks:
    file: config.yml
  notify: Restart and Enable Netdata
