---
- name: Netdata KSM | Enable Kernel Same-Page Merging
  become: true
  lineinfile:
    line: "{{ item }}"
    path: /etc/rc.local
  loop:
    - echo 1 >/sys/kernel/mm/ksm/run
    - echo 1000 >/sys/kernel/mm/ksm/sleep_millisecs
