---
- name: Include Dynamic Variables Task
  include_tasks:
    file: dynamic-var.yml

- name: Check If Netdata Is Installed
  become: true
  stat:
    path: "{{ netdata_service_installation }}"
  register: netdata_installed

- name: Include Main Netdata Install Task
  include_tasks:
    file: install.yml
  when:
    - not netdata_uninstall | bool
    - not netdata_installed.stat.exists | bool

- name: Include Netdata Uninstaller (If Configured)
  include_tasks:
    file: uninstall.yml
  when:
    - netdata_uninstall | bool
    - netdata_installed.stat.exists | bool
  tags: ["netdata_uninstall"]
