---
- name: Include Monitor Fail2ban Task
  include_tasks:
    file: monitor-fail2ban.yml
  when:
    - not netdata_uninstall
    - netdata_monitor_fail2ban

- name: Include Monitor IPMI Task
  include_tasks:
    file: monitor-ipmi.yml
  when:
    - not netdata_uninstall
    - netdata_monitor_ipmi

- name: Include Build Sequence of Installation Command
  include_tasks:
    file: install-cmd.yml
  when: not netdata_uninstall

- name: Include Kernel Same-Page Merging Task
  include_tasks:
    file: ksm.yml
  when:
    - not netdata_uninstall
    - netdata_opt_enable_ksm

- name: Include Main Netdata Install Task
  include_tasks:
    file: install.yml
  when: not netdata_uninstall

- name: Include Configuration File
  include_tasks:
    file: config.yml
  notify: Restart and Enable Netdata
  when: not netdata_uninstall

- name: Include Netdata Uninstaller (If Configured)
  include_tasks:
    file: uninstall.yml
  when: netdata_uninstall
  tags:
    - netdata_uninstall
