---
- include_vars:
    file: install-cmd-options.yml
  when: netdata_install_options is defined

- include_tasks:
    file: install.yml

- include_tasks:
    file: uninstall.yml
  when: netdata_uninstall
  tags:
    - netdata_uninstall
