---
- include_vars:
    file: "{{ ansible_service_mgr }}.yml"

- include_vars:
    file: install-cmd-options.yml
  when:
    - netdata_install_options | length > 0
    - netdata_uninstall == false

- include_tasks:
    file: install.yml
  when: netdata_uninstall == false

- include_tasks:
    file: uninstall.yml
  when: netdata_uninstall
  tags:
    - netdata_uninstall
