---
- name: Include Dynamic Variables Task
  import_tasks:
    file: dynamic-var.yml
  tags: ["netdata_install", "netdata_uninstall"]

- name: Check If Netdata Is Installed
  become: true
  stat:
    path: "{{ netdata_service_installation }}"
  register: netdata_installed
  tags: ["netdata_install", "netdata_uninstall"]

- name: Include Main Netdata Install Task
  import_tasks:
    file: install.yml
  when:
    - not netdata_uninstall | bool
    - not netdata_installed.stat.exists | bool
  tags: ["netdata_install"]

- name: Include Configuration File
  import_tasks:
    file: config.yml
  when: not netdata_uninstall | bool
  tags: ["netdata_install"]

- name: Include Netdata Uninstaller (If Configured)
  import_tasks:
    file: uninstall.yml
  when:
    - netdata_uninstall | bool
    - netdata_installed.stat.exists | bool
  tags: ["netdata_uninstall"]
