---
- name: Ensure Apt Cache Is up to Date (debian)
  become: true
  apt:
    update_cache: true
    cache_valid_time: 360
  when:
    - ansible_os_family == 'Debian'

- name: Ensure Netdata Dependencies Are Present (General)
  become: true
  package:
    name:
      - autoconf
      - autogen
      - automake
      - curl
      - gcc
      - git
      - libmnl-dev
      - make
      - pkg-config
    state: present

- name: Ensure Netdata Dependencies Are Present (Debian)
  become: true
  apt:
    name:
      - autoconf-archive
      - libmnl-dev
      - pkg-config
      - uuid-dev
      - zlib1g-dev
    state: present
    update_cache: true
    cache_valid_time: 360
  when:
    - ansible_os_family == 'Debian'

- name: Ensure Netdata Dependencies Are Present (Fedora)
  become: true
  dnf:
    name:
      - autoconf-archive
      - findutils
      - libmnl-devel
      - libuuid-devel
      - pkgconfig
      - zlib-devel
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'Fedora'

- name: Ensure Netdata Dependencies Are Present (RedHat)
  become: true
  yum:
    name:
      - libmnl-devel
      - libuuid-devel
      - lm_sensors
      - MySQL-python
      - nc
      - pkgconfig
      - python
      - python-psycopg2
      - PyYAML
      - zlib-devel
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

- name: Ensure Netdata Github Repo Is Up To Date
  become: true
  git:
    repo: https://github.com/netdata/netdata.git
    dest: "{{ netdata_root_install_dir }}/netdata"
    version: "{{ netdata_repo_version }}"
    depth: 100
    force: true
  notify: Ensure Netdata Is Installed and up to Date
