---
- name: Ensure Netdata IPMI Monitoring Dependencies (Apt)
  become: true
  package:
    name: libipmimonitoring-dev
    state: present
  when:
    - ansible_os_family | lower == 'debian'
    - ansible_distribution | lower == 'ubuntu'

- name: Ensure Netdata IPMI Monitoring Dependencies (Yum)
  become: true
  package:
    name: freeipmi-devel
    state: present
  when: ansible_os_family | lower == 'redhat'
