---
- name: Run Netdata Uninstaller Script
  become: true
  command: "./{{ netdata_uninstaller.sh }} -y -f -e {{ netdata_uninstaller.env }}"
  args:
    chdir: "{{ netdata_uninstaller.path }}"

- name: Remove Netdata GitHub Repo
  become: true
  file:
    path: "{{ netdata_source_dir }}"
    state: absent
