---
- name: Run Netdata Uninstaller Script
  command: "./{{ netdata_uninstaller.sh }} -y -f -e {{ netdata_uninstaller.env }}"
  args:
    chdir: "{{ netdata_uninstaller.path }}"

- name: Remove Netdata GitHub Repo
  file:
    state: absent
    path: "{{ netdata_source_dir }}"
