---
- name: Stop Netdata If Present
  become: true
  listen: Install Netdata
  service:
    name: netdata
    state: stopped
  ignore_errors: true

- name: Ensure Netdata Is Installed and up to Date
  listen: Install Netdata
  become: true
  command: "./netdata-installer.sh --dont-wait --dont-start-it"
  args:
    chdir: "{{ netdata_source_dir }}"
    creates: /usr/sbin/netdata

- name: Start and Enable Netdata
  become: true
  listen: Install Netdata
  service:
    name: netdata
    state: restarted
    enabled: true
