---
- name: Ensure Netdata Is Installed and up to Date
  become: true
  shell: "./netdata-installer.sh --install {{ netdata_root_install_dir }} --dont-wait"
  args:
    chdir: "{{ netdata_root_install_dir }}/netdata"
