---
- name: Check for Existing Netdata Service
  become: true
  listen: Install Netdata
  stat:
    path: /usr/lib/systemd/system/netdata.service
  register: netdata_service

- name: Stop Netdata Service If Present
  become: true
  service:
    name: netdata
    state: stopped
  when: netdata_service.stat.exists == true

- name: Ensure Netdata Is Installed and up to Date
  become: true
  listen: Install Netdata
  command: "{{ netdata_install_cmd }}"
  args:
    chdir: "{{ netdata_source_dir }}"
    creates: /usr/sbin/netdata

- name: Start and Enable Netdata
  become: true
  listen: Install Netdata
  service:
    name: netdata
    state: restarted
    enabled: true
