---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Gathering Facts
      become: false
      setup:
        gather_subset:
          - '!all'
          - network
          - hardware
  roles:
    - role: geerlingguy.repo-epel
    - role: hwwilliams.netdata
