---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Gathering Facts
      become: false
      setup:
        gather_subset:
          - '!all'
          - network
          - hardware
  roles:
    - role: hwwilliams.epel
      when:
        - ansible_os_family | lower == 'redhat'
        - not ansible_distribution | lower == 'fedora'
    - role: hwwilliams.netdata
